name: Xcode build iOS 17

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode iOS build
      run: |
        cd Xcode/
        xcodebuild clean build -scheme TheNews -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
